// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

#nullable disable

namespace Persistencia.Data.Migrations
{
    [DbContext(typeof(RetoWebApiContext))]
    [Migration("20230906015402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dominio.Entities.Equipo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdPaisFK")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdPaisFK");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Dominio.Entities.Jugador", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Dorsal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("IdPersonaFK")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdPosicionFK")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonaFK")
                        .IsUnique();

                    b.HasIndex("IdPosicionFK");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Dominio.Entities.Pais", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Dominio.Entities.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdEquipoFK")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdTipoNominaFK")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipoFK");

                    b.HasIndex("IdTipoNominaFK");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Dominio.Entities.Posicion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NombrePosicion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posiciones");
                });

            modelBuilder.Entity("Dominio.Entities.TipoNomina", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NombreNomina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposNominas");
                });

            modelBuilder.Entity("Dominio.Entities.Equipo", b =>
                {
                    b.HasOne("Dominio.Entities.Pais", "Pais")
                        .WithMany("Equipos")
                        .HasForeignKey("IdPaisFK");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Dominio.Entities.Jugador", b =>
                {
                    b.HasOne("Dominio.Entities.Persona", "Persona")
                        .WithOne("Jugador")
                        .HasForeignKey("Dominio.Entities.Jugador", "IdPersonaFK");

                    b.HasOne("Dominio.Entities.Posicion", "Posicion")
                        .WithMany("Jugadores")
                        .HasForeignKey("IdPosicionFK");

                    b.Navigation("Persona");

                    b.Navigation("Posicion");
                });

            modelBuilder.Entity("Dominio.Entities.Persona", b =>
                {
                    b.HasOne("Dominio.Entities.Equipo", "Equipo")
                        .WithMany("Personas")
                        .HasForeignKey("IdEquipoFK");

                    b.HasOne("Dominio.Entities.TipoNomina", "TipoNomina")
                        .WithMany("Personas")
                        .HasForeignKey("IdTipoNominaFK");

                    b.Navigation("Equipo");

                    b.Navigation("TipoNomina");
                });

            modelBuilder.Entity("Dominio.Entities.Equipo", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Dominio.Entities.Pais", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Dominio.Entities.Persona", b =>
                {
                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Dominio.Entities.Posicion", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("Dominio.Entities.TipoNomina", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
